services:
  backend-dev:
    build:
      context:
      dockerfile: backend/dockerfile/file.backend
      target: dev
      volumes:
      - ./backend/app
      ports:
       - "4000:4000"
       environment:
       - NODE_ENV=development
       - MONGO_URI=mongodb://db:27017/mern
       depends_on:
         -db

frontend-dev:
 build:
   context:
   dockerfile: backend/Dockerfile.backend
   target: dev
   db:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mern_db:/data/db

  
