# Development stage
FROM node:22-alpine as dev

# define working dir
WORKDIR /src

# copy package.json and package-lock.json to container
COPY backend/package.json ./ 
RUN npm install

# Copy all files to container
COPY backend/ .
EXPOSE 3000
CMD ["npm", "run", "start"]

FROM node:22-alpine as prod

COPY backend/package.json ./ 
RUN npm install

COPY backend/ .
